---
- name: 'Unregister SLES'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'b1-systems-ansible-role-suseconnect'
      vars:
        suseconnect_remove_subscriptions: 'true'
      when: 'ansible_distribution == "SLES"'
